export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const LIST_CATEGORIES_SUCCESS = 'LIST_CATEGORIES_SUCCESS';
export const DELETE_CATEGORY ="DELETE_CATEGORY"
export const DELETE_CATEGORY_SUCCESS ="DELETE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY ="UPDATE_CATEGORY"
export const UPDATE_CATEGORY_SUCCESS ="UPDATE_CATEGORY_SUCCESS"
